// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://telbgdeasjctemqinsue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbGJnZGVhc2pjdGVtcWluc3VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNzMzODIsImV4cCI6MjA1NDg0OTM4Mn0.67cIlo82WZeBJ23u_klntTQkXFc3n00hg5cUVtGAiN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);